name: servant-oidc
version: 0.1.1.1
category: Web
author: NoRedInk
maintainer: eng@noredink.com
copyright: 2017 NoRedInk
license: BSD3
dependencies:
  - aeson >= 1.3.1.1 && < 2.2
  - base >= 4.11.1.0 && < 4.19
  - cereal >= 0.5.7.0 && < 0.6
  - jose-jwt >= 0.7.8 && < 0.10
  - http-api-data >= 0.3.8.1 && < 0.6
  - network-uri >= 2.6.1.0 && < 2.7
  - servant >= 0.14.1 && < 0.20
  - text >= 1.2.3.1 && < 2.1
ghc-options:
  - -Wall
  - -Werror
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - TypeOperators
library:
  source-dirs: src
