_root-package-yaml: !include "../../package.yaml"
name: servant-oidc
version: '0.1.0.0'
category: Web
author: NoRedInk
maintainer: eng@noredink.com
copyright: 2017 NoRedInk
license: BSD3
dependencies:
- aeson == 1.2.3.0
- aeson-casing == 0.1.0.5
- base == 4.10.1.0
- bytestring == 0.10.8.2
- cereal == 0.5.5.0
- jose-jwt == 0.7.8
- http-api-data == 0.3.7.1
- http-types == 0.9.1
- network-uri == 2.6.1.0
- protolude == 0.2.1
- servant == 0.11
- servant-auth-server == 0.3.1.0
- servant-server == 0.11.0.1
- text == 1.2.2.2
ghc-options:
- -Wall
- -Werror
default-extensions: *default-extensions
library:
  source-dirs: src
