_root-package-yaml: !include "../../package.yaml"
name: servant-oidc
version: '0.1.0.0'
category: Web
author: NoRedInk
maintainer: eng@noredink.com
copyright: 2017 NoRedInk
license: BSD3
dependencies:
- aeson == 1.1.2.0
- aeson-casing == 0.1.0.5
- base >=4.7 && <5
- bytestring == 0.10.8.1
- cereal == 0.5.4.0
- jose-jwt == 0.7.7
- hashable == 1.2.6.1
- http-api-data == 0.3.7.1
- http-types == 0.9.1
- network-uri == 2.6.1.0
- protolude == 0.1.10
- servant == 0.11
- servant-auth-server
- servant-server == 0.11
- text == 1.2.2.2
ghc-options:
- -Wall
- -Werror
default-extensions: *default-extensions
library:
  source-dirs: src
