_root-package-yaml: !include "../../package.yaml"
name: servant-oidc
version: '0.1.0.0'
category: Web
author: NoRedInk
maintainer: eng@noredink.com
copyright: 2017 NoRedInk
license: BSD3
dependencies:
- aeson == 1.1.2.0
- aeson-casing == 0.1.0.5
- base >=4.7 && <5
- base64-bytestring == 1.0.0.1
- bytestring == 0.10.8.1
- cereal == 0.5.4.0
- cryptonite == 0.23
- data-default == 0.7.1.1
- entropy == 0.3.8
- exceptions == 0.8.3
- jose-jwt == 0.7.7
- oidc-client == 0.3.0.1
- oops
- http-api-data == 0.3.7.1
- http-client == 0.5.7.0
- http-link-header == 1.0.3
- http-media == 0.6.4
- http-types == 0.9.1
- mtl == 2.2.1
- network-uri == 2.6.1.0
- network-uri-static == 0.1.0.0
- postgresql-typed == 0.5.1
- protolude == 0.1.10
- QuickCheck == 2.9.2
- quickcheck-instances == 0.3.12
- servant == 0.11
- servant-auth-cookie == 0.5.0.5
- servant-client == 0.11
- servant-auth-server
- servant-elm == 0.4.0.1
- servant-foreign == 0.10.1
- servant-quickcheck == 0.0.3.1
- servant-server == 0.11
- text == 1.2.2.2
- wai == 3.2.1.1
ghc-options:
- -Wall
- -Werror
default-extensions: *default-extensions
library:
  source-dirs: src
